export const SWAGGER_EXAMPLE_FIRE_RESISTANT = {
    reminding: true,
    seepage_liquid: "Хлорка ;)",
    area: 450,
    next_check: "02.05.2023"
}

export const SWAGGER_EXAMPLE_FIRE_RESISTANT_IMPREGNATION = {
    id: 1,
    ...SWAGGER_EXAMPLE_FIRE_RESISTANT
}

export const SWAGGER_EXAMPLE_FIRE_RESISTANT_IMPREGNATION_LIST = [
    SWAGGER_EXAMPLE_FIRE_RESISTANT_IMPREGNATION,
    SWAGGER_EXAMPLE_FIRE_RESISTANT_IMPREGNATION
]