export const SWAGGER_EXAMPLE_FIRE_EXTINGUISHER_BODY = {
    reminding: true,
    seepage_liquid: "Хлорка ;)",
    area: 450,
    next_check: "02.05.2023"
}

export const SWAGGER_EXAMPLE_FIRE_EXTINGUISHER = {
    id: 1,
    ...SWAGGER_EXAMPLE_FIRE_EXTINGUISHER_BODY
}

export const SWAGGER_EXAMPLE_FIRE_EXTINGUISHER_LIST = [
    SWAGGER_EXAMPLE_FIRE_EXTINGUISHER,
    SWAGGER_EXAMPLE_FIRE_EXTINGUISHER
]