export enum Exception {
    UNATHORIZED = 'Unathorized',
    FORBIDDEN = "Forbidden. Credentials incorrect",
    CARD_NOT_FOUND = " Card with this ID does not found",
    USER_NOT_FOUND = " User with this ID does not found",
    POSITION_NOT_FOUND = " Position with this ID does not found",
    CAR_NOT_FOUND = " Car with this ID does not found",
    SIM_CARD_NOT_FOUND = " Sim card with this ID does not found",
    OBSERVATION_NOT_FOUND = " Observation with this ID does not found",
    FIRE_HYDRANT_NOT_FOUND = " Fire hydrant with this ID does not found",
    FIRE_HYDRANT_OR_FIRM_NOT_FOUND = " Fire hydrant or firm with this ID does not found",
    FIRE_RESISTANT_IMPREGNATION_NOT_FOUND = " Fire resistant impregnation with this ID does not found",
    FIRE_EXTINGUISHER_NOT_FOUND = " Fire extinguishers with this ID does not found",
    CONTACT_PERSON_NOT_FOUND = " Contact person with this ID does not found",
    FIRM_CLIENT_NOT_FOUND = " Firm client with this ID does not found",
}